export const cardContent = [
  {
    picNum: 1,
    headingNum: 1,
    backNum: 1,
    title: "Forkify",
    slugA: "React",
    slugB: "Javascript",
    slugC: "CSS3",
    slugD: "API",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$297",
    projectLink: "forkify-john.netlify.app",
  },
  {
    picNum: 2,
    headingNum: 3,
    backNum: 3,
    title: "Bankist",
    slugA: "React",
    slugB: "Javascript",
    slugC: "CSS3",
    slugD: "API",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$297",
    projectLink: "plunky33.github.io/bankist",
  },
  {
    picNum: 3,
    headingNum: 1,
    backNum: 1,
    title: "The Pig Game",
    slugA: "React",
    slugB: "Javascript",
    slugC: "CSS3",
    slugD: "API",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$297",
    projectLink: "plunky33.github.io/pig-game",
  },
  {
    picNum: 4,
    headingNum: 1,
    backNum: 1,
    title: "The MovieDB App",
    slugA: "React",
    slugB: "Javascript",
    slugC: "CSS3",
    slugD: "API",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$297",
    projectLink: "moviedb-react-app.netlify.app",
  },
  {
    picNum: 5,
    headingNum: 3,
    backNum: 3,
    title: "The Budgety App",
    slugA: "Module Pattern",
    slugB: "Vanilla Javascript",
    slugC: "CSS3",
    slugD: "API",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$297",
    projectLink: "budgety-vanillajs-app.netlify.app",
  },
  {
    picNum: 6,
    headingNum: 1,
    backNum: 1,
    title: "The Youtubey App",
    slugA: "React",
    slugB: "Javascript",
    slugC: "CSS3",
    slugD: "API",
    slugE: "Difficulty: Easy",
    backTitle: "Only",
    backSubtitle: "$297",
    projectLink: "youtubey-react.netlify.app/",
  },
];
